# Generated by Django 5.1.6 on 2025-07-19 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myspace.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myspace.product')),
            ],
        ),
    ]
